name: ci

on:
  push:
    branches:
      - main

  pull_request:

defaults:
  run:
    # NOTE: A bit stricter than the default bash options used by GitHub Actions
    shell: bash --noprofile --norc -euo pipefail {0}

jobs:
  validate-json:
    name: Validate JSON

    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Verify that json schema can be used for validation
        env:
          # renovate: datasource=pypi depName=check-jsonschema
          CHECK_JSONSCHEMA_VERSION: 0.37.0
        run: |
          pip install --quiet "check-jsonschema==$CHECK_JSONSCHEMA_VERSION"
          check-jsonschema --schemafile "gp-cicd/schema.json" ".gp.cicd.example.json"
