name: ci

on:
  push:
    branches:
      - main

  pull_request:

defaults:
  run:
    # NOTE: A bit stricter than the default bash options used by GitHub Actions
    shell: bash --noprofile --norc -euo pipefail {0}

jobs:
  validate-json:
    name: Validate JSON

    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Verify that json schema can be used for validation
        env:
          # renovate: datasource=pypi depName=check-jsonschema
          CHECK_JSONSCHEMA_VERSION: 0.37.0
        run: |
          pip install --quiet "check-jsonschema==$CHECK_JSONSCHEMA_VERSION"
          check-jsonschema --schemafile "gp-cicd/schema.json" "gp-cicd/.gp.cicd.only-dev.json"
          check-jsonschema --schemafile "gp-cicd/schema.json" "gp-cicd/.gp.cicd.full.json"
